version: "3"

services:
  mediators:
    build:
      context: .
    ports:
      - "8002:8002"
    volumes:
      - ./mediators:/mediators
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8002"                                               




