version: "3"

services:
  mediators:
    build:
      context: .
    ports:
      - "8000:8000"
      - "8080"
    volumes:
      - ./mediators:/mediators
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000" 
