apiVersion: v1
kind: Secret
metadata:
  name: myapp-secret
type: Opaque
data:
  DJANGO_SUPERUSER_USERNAME: ZZZZZZ # Base64 encoded value of 'admin'
  DJANGO_SUPERUSER_EMAIL: ZZZZZZ= # Base64 encoded value of 'email'
  DJANGO_SUPERUSER_PASSWORD: ZZZZZZ= # Base64 encoded value of 'password'
